language: java

dist: trusty

jdk:
  - oraclejdk11

install: true

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/.i18nExtractor

before_install:
  - chmod +x gradlew

script:
  ./gradlew pack uploadArtifacts