# the configuration version (do not change this)
version: 1

# How long (in ticks, 20ticks/second) to wait after someone opens a backpack before they can open it again
openBackpackCooldown: 8

# What language to set the plugin to. You can compile the plugin to support any languages you wish. For more info, see the github.
# Current included languages are: en (English), es (Spanish)
language: en

recipes:
  small:
    ingredients:
      A: OAK_PLANKS
      B: LEATHER
    shape:
      - "AAA"
      - "ABA"
      - "AAA"
  large:
    ingredients:
      A: OAK_LOG
      B: IRON_INGOT
    shape:
      - "AAA"
      - "ABA"
      - "AAA"
  linked:
    ingredients:
      A: DIAMOND
      B: LEATHER
      C: ENDER_EYE
      D: IRON_INGOT
    shape:
      - "ADA"
      - "BCB"
      - "ADA"
  backpack_key:
    ingredients:
      A: IRON_INGOT
      B: FEATHER
    shape:
      - "  A"
      - " BA"
      - " AA"